[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.4", features = ["full","node-bindings"] }
dotenv = "0.15.0"
env_logger = "0.11.3"
eyre = "0.6.5"
log = "0.4.14"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.14.0", features = ["full"] }



